version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "23:00"
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/blog"
  schedule:
    interval: daily
    time: "23:00"
  open-pull-requests-limit: 10
