# Sidebar configurations.
# Please be noted that a sidebar is only visible when it has at least one widget
sidebar:
    null

# Sidebar widget configurations
# http://ppoffice.github.io/hexo-theme-icarus/categories/Widgets/
widgets:
    null
