name: PR Status

on:
  pull_request:
    branches:
      - master

jobs:
  test_and_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm run all-install
      #- run: npx hexo algolia
      #  env:
      #    HEXO_ALGOLIA_INDEXING_KEY: ${{ secrets.HEXO_ALGOLIA_INDEXING_KEY }}
      - run: NODE_ENV=production npm run build
